# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

trigger:
  branches:
    include:
      - main
      - develop
      - release-*
  paths:
    exclude:
      - .github_changelog_generator
      - .gitignore
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE.md
      - README.md
      - NuGet.Config
      - assets/*
      - config/*
      - .github/*

# PR always trigger build
pr:
  autoCancel: true

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build job'
    pool:
      # default is the following VM Image
      vmImage: 'windows-latest'
      # playing with TestStream pool
      #name: TestStream

    variables:
      DOTNET_NOLOGO: true
      solution: 'nanoFramework.IoT.TestStream.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      nugetPackageName: 'nanoFramework.IoT.TestStream'

    steps:

    # step from template @ nf-tools repo
    # only build and run tests
    - template: azure-pipelines-templates/class-lib-build-only.yml@templates
      parameters:
        runUnitTests: false
        unitTestRunsettings: '$(System.DefaultWorkingDirectory)\.runsettings'
        #sonarCloudProject: 'nanoframework_lib-nanoFramework.IoT.TestStream'
        skipSonarCloudAnalysis: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact copy
      inputs:
        path: '$(System.DefaultWorkingDirectory)\nanoFramework.IoT.TestStream'
        artifactName: 'Artifacts'

- stage: Test
  displayName: 'Test'
  jobs:
  - job: Test
    displayName: 'Test job'
    pool:
      name: TestStream

    steps:

    - script: echo 'Testing'
      displayName: 'Testing'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        path: '$(System.DefaultWorkingDirectory)\nanoFramework.IoT.TestStream'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet custom'
      inputs:
        command: custom
        projects: '**/*Test*.dll'
        custom: vstest
        arguments: '--logger:trx;logfilename=TEST.xml'
      timeoutInMinutes: 120
