# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

trigger:
  branches:
    include:
      - main
      - develop
      - release-*
  paths:
    exclude:
      - .github_changelog_generator
      - .gitignore
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE.md
      - README.md
      - NuGet.Config
      - assets/*
      - config/*
      - .github/*

# PR always trigger build
pr:
  autoCancel: true

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build job'
    pool:
      # default is the following VM Image
      vmImage: 'windows-latest'
      # playing with TestStream pool
      #name: TestStream

    variables:
      DOTNET_NOLOGO: true
      solution: 'nanoFramework.IoT.TestStream.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      nugetPackageName: 'nanoFramework.IoT.TestStream'

    steps:

    # step from template @ nf-tools repo
    # only build and run tests
    - template: azure-pipelines-templates/class-lib-build-only.yml@templates
      parameters:
        runUnitTests: false
        unitTestRunsettings: '$(System.DefaultWorkingDirectory)\.runsettings'
        #sonarCloudProject: 'nanoframework_lib-nanoFramework.IoT.TestStream'
        skipSonarCloudAnalysis: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact copy
      inputs:
        path: '$(System.DefaultWorkingDirectory)'
        artifactName: 'Artifacts'

- stage: Test
  displayName: 'Test'
  jobs:
  - job: Test
    displayName: 'Test job'
    pool:
      name: TestStream

    steps:

    - script: echo 'Testing'
      displayName: 'Testing'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifact'
      inputs:
        path: '$(System.DefaultWorkingDirectory)'

    - script:  mono /azp/TestPlatform/vstest.console.exe $(System.DefaultWorkingDirectory)/Artifacts/UnitTestStream/bin/Release/NFUnitTest.dll /Settings:$(System.DefaultWorkingDirectory)/Artifacts/UnitTestStream/nano.runsettings /TestAdapterPath:/azp/_work/1/$(System.DefaultWorkingDirectory)/Artifacts/packages/nanoFramework.TestFramework.2.1.111/ /Logger:trx;LogFileName=TEST.xml
      displayName: 'Run tests'
      timeoutInMinutes: 120
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest' # 'JUnit' | 'NUnit' | 'VSTest' | 'XUnit' | 'CTest'. Alias: testRunner. Required. Test result format. Default: JUnit.
        testResultsFiles: '**/*.trx'

    - displayName: Cleaning tests results
      bash: |
        # Define the subdirectory path
        SUBDIRECTORY_PATH="$(System.DefaultWorkingDirectory)"

        # Find and remove all .trx files in the subdirectory
        find "$SUBDIRECTORY_PATH" -type f -name "*.trx" -exec rm -f {} \;

        # Optional: Print a message indicating completion
        echo "All .trx files have been removed from $SUBDIRECTORY_PATH"